src/feisgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('accounts/signup', signup, name='account_signup'),
    path('profiles/', include('profiles.urls', namespace = 'profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from .views import post_comment_create_list, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list, name = 'main-post-view'),
    path('liked/', like_unlike_post, name = 'like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

src/profiles/urls.py
from django import views
from django.urls import path 
from .views import (
    all_friends_view,
    delete_friend,
    my_profile_view, 
    invites_received_view, 
    profiles_free_to_send_invites,
    ProfileDetailView,
    ProfileListView,
    search_friend,
    send_invitation,
    accept_invitation,
    reject_invitation,
    show_profile,
    chat,
    change_password
)

app_name = 'profiles'
'''
    Definendo tale path è come se indicassi --> http://127.0.0.1/profiles/myprofile
'''
urlpatterns = [
    path('', ProfileListView.as_view(), name='all-profiles-view'),
    path('myprofile/', my_profile_view, name = 'my-profile-view'),
    path('myinvites/', invites_received_view, name='my-invites-view'),
    path('toinvites/', profiles_free_to_send_invites, name='to-invite-view'),
    path('sendinvite/', send_invitation, name='send-invite'),
    path('myfriends/',all_friends_view,name='my-friends-view'),
    path('removefriend/', delete_friend, name='delete-friend-view'),
    path('searchfriend/', search_friend, name='search-friend-view'),
    path('showprofile/',show_profile, name='show-profile'),
    path('chat/', chat , name='chat-view'),
    path('sendmessage/', chat, name="send-message"),
    path('changepwd/',change_password, name='change-password'),
    path('changepwdversion/',change_password, name='change-password-view'),
    path('<slug>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('myinvites/accept/', accept_invitation, name='accept-invite'),
    path('myinvites/acceptversion/', accept_invitation, name='accept-invite-view'),
    path('myinvites/reject/', reject_invitation, name='reject-invite'),
]

src/profiles/forms.py
from django import forms
from .models import Profile 

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile 
        fields = ('first_name','last_name', 'country','bio','avatar')

src/profiles/views.py
from email import message
from logging import NullHandler
from multiprocessing import current_process
from unittest import result
from urllib import request
from webbrowser import get
from django.dispatch import receiver
from django.shortcuts import render, redirect, get_object_or_404
from matplotlib.style import context
from .models import Profile, Relationship, Message
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

'''
    View per la creazione del profilo
'''

@login_required
def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    '''
        Metodo che mi permette di emanare un segnale se il form è stato aggiornato correttamente
    '''
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True 

    context = {
        'profile' : profile,
        'form' : form,
        'confirm' : confirm,
    }

    return render(request, 'profiles/myProfile.html', context)

'''
    View per la visualizzazione delle richieste di amicizia ricevute
'''

@login_required
def invites_received_view(request):
    '''
        Profilo corrente
    '''
    profile = Profile.objects.get(user=request.user)
    '''
        Query che filtra tutte le richieste di amicizia del profilo corrente
    '''
    qs = Relationship.objects.invites_received(profile)

    results = list(map(lambda x: x.sender, qs))

    is_empty = False
    if len(results) == 0:
        is_empty = True

    context = {
        'qs' : results,
        'is_empty': is_empty,
    }

    return render(request, 'profiles/myInvites.html', context)


@login_required
def all_friends_view(request):
    ''' Utente corrente'''
    user = request.user
    is_empty = False
    ''' Prelevo le informazioni dell'utente collegato '''
    results = Profile.objects.filter(user=user)
    ''' Prelevo la lista degli amici '''
    allFriends = list(results[0].friends.all())
    ''' Per ogni amico dell'utente collegato salvo il profilo in una lista '''
    qs = []
    for i in allFriends:
        qs.append(Profile.objects.get(user=i))
    if(len(qs) == 0):
        is_empty = True
    else:
        is_empty = False

    context = {
        'qs': qs,
        'is_empty': is_empty,
    }

    return render(request, 'profiles/myFriends.html', context)

'''
    View per accettare le richieste di amicizia
'''
@login_required
def accept_invitation(request):
    path = ''
    print(request.path)
    if request.path == '/profiles/myinvites/accept/':
        path = 'profiles:my-invites-view'
    elif request.path == '/profiles/myinvites/acceptversion/':
        path = 'profiles:my-friends-view'

    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect(path)



'''
    View per rifiutare richieste di amicizia
'''
@login_required
def reject_invitation(request):
    if request.method == "POST":
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my-invites-view')

'''
    View per la cancellazione di un utente
'''
@login_required 
def delete_friend(request):
    path = ''
    if request.path == '/profiles/removefriend/':
        path = 'profiles:my-friends-view'
    elif request.path == '/profiles/removefriendversion/':
        path = 'profiles:search-friend-view'

    if request.method == "POST":
        # Prelevo la chiave primari dell'utente che voglio rimuovere
        pk = request.POST.get('profile_pk')
        # Prelevo l'utente collegato
        currentUser = Profile.objects.get(user=request.user)
        # Ricerco il profilo all'interno della tabella, generando una ricerca in base alla chiave primaria
        profile = get_object_or_404(Profile,pk=pk)
        # Prelevo la lista completa di tutti gli amici dell'utente collegato
        allFriends = list(currentUser.friends.all())
        # Prelevo la relazione che associa l'utente collegato all'utente che si vuole eliminare
        rel = Relationship.objects.filter(status='accepted', sender=profile) \
                | Relationship.objects.filter(status='accepted', receiver=profile)
        # Prelevo tutti i messaggi tra l'utente corrente e l'utente che voglio cancellare
        messages = Message.objects.filter(sender_message=currentUser, receiver_message=profile) \
                    | Message.objects.filter(sender_message=profile,receiver_message=currentUser).order_by('-created')
        # Cerco all'interno della lista degli amici dell'utente corrente, l'utente che dovrà essere eliminato
        for i in allFriends:
            # Quando lo trovo
            if i == profile.user:
                # Elimino l'utente dalla lista degli amici dell'utente corrente
                currentUser.friends.remove(i)
                # Elimino la relazione che lega i due utenti nella tabella Relationship 
                rel.delete()
                # Elimino tutti i messaggi
                messages.delete()
    return redirect(path)

''' Ricerca amico '''
@login_required
def search_friend(request):
    # Prelevo il pattern di ricerca inserito nell'input box 
    pattern = request.GET.get('search')
    isEmpty = False
    results = []
    # Se il pattern esiste
    if pattern:
        # Cerco tutti i profili che hanno come pattern iniziale, quello passato .. la ricerca avviene sia per nome che per cognome
        # escludendo l'utente collegato
        results = Profile.objects.filter(first_name__startswith=pattern).exclude(user=request.user) \
                    | Profile.objects.filter(last_name__startswith=pattern).exclude(user=request.user)
        if not results:
            # Se non ci sono risultati, viene mostrato un messaggio
            isEmpty = True
    context = {
        'results': results,
        'isEmpty': isEmpty
    }
    return render(request, 'profiles/search.html', context)
    
''' Informazioni profilo ricercato '''
@login_required
def show_profile(request):
    currentUser = Profile.objects.get(user=request.user)
    check = False
    req = False
    notFriend = False
    # Prelevo la chiave primario dell'utente al quale vogli visuallizzare il profilo
    pk = request.POST.get('profile_pk')
    # Prelevo le sue informazioni tramite un'interrogazione al database
    profile = Profile.objects.get(pk=pk)

    # Se l'utente corrente ha inviato la richiesta all'utente Profile
    if (Relationship.objects.filter(status='send',sender=currentUser, receiver=profile)):
        req = True; check = False; notFriend = False;
    # Se l'utente Profile ha inviato la richiesta all'utente corrente
    elif (Relationship.objects.filter(status='send',sender=profile, receiver=currentUser)):
        req = False; check = False; notFriend = False;
    # Se tra l'utente corrente e l'utente profile è già stato stretto un rapporto di amicizia
    elif (Relationship.objects.filter(status='accepted',sender=currentUser, receiver=profile)) \
            | (Relationship.objects.filter(status='accepted',sender=profile, receiver=currentUser)):
        req = False; check = True; notFriend = False;
    # Se l'utente corrente e l'utente profilo non hanno niente a che fare l'uno con l'altro
    else:
        req = False; check = False; notFriend = True;

    context = {
        'profile': profile,
        'check': check,
        'req': req,
        'notFriend': notFriend
    }
    return render(request,'profiles/searchedProfileInfo.html', context)

'''
    View per la visualizzazione di tutti i profili presenti nel sistema dove l'utente collegato ha la possibilità
    di inviare una richiesta di amicizia
'''

@login_required
def profiles_free_to_send_invites(request):
    '''
        Utente corrente 
    '''
    user = request.user
    '''
        Query per la visualizzazione di tutti i profili presenti nel sistema escluso quello collegato e tutti i suoi amici 
    '''
    qs = Profile.objects.get_all_profiles_free_to_invite(user)

    context = {
        'qs' : qs,
    }

    return render(request, 'profiles/toInvites.html', context)

@login_required
def all_profiles_exclude_me(request):
    '''
        Utente corrente 
    '''
    user = request.user
    '''
        Query per la visualizzazione di tutti i profili presenti nel sistema escluso quello collegato
    '''
    qs = Profile.objects.get_all_profiles_exclude_me(user)

    context = {
        'qs' : qs,
    }

    return render(request, 'profiles/allProfiles.html', context)

''' Messaggistica '''
@login_required
def chat(request):
    # Lista vuota per memorizzare tutti gli amici con cui è iniziata una conversazione
    getAllFriendWithConversation = []
    # Lista vuota per contare il numero di messaggi in entrata 
    list_occurence_message = []
    # Utente corrente
    currentUser = Profile.objects.get(user=request.user)

    # Questa porzione di codice viene eseguita solo se viene visualizzata una conversazione in particolare tra gli utenti
    # con cui è iniziata una conversazione
    if request.POST.get('profile_pk'):
        # Prelevo la chiave del profilo di cui voglio visualizzare la conversazione
        pk = request.POST.get('profile_pk')
        # Prelevo dal DB l'utente in base alla chiave

src/profiles/templates/profiles/allProfiles.html
{% extends 'base.html' %}

{% block title %} All profiles  {% endblock title %}

{% block content %}

{% if is_empty %}
    <h1> No profile </h1>
{% endif %}

<div class="row">
<div class="col-md-2"></div>
<div id="conteinerPosts" class="col-md-8">
    {% for obj in object_list %}
      <div id="Cposts" class="col-md-12">
        <div class="media g-mb-30 media-comment">
            <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
                <div class="row">
                    <div class="col-md-3" align="left">
                        <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15" src={{obj.avatar.url}}></img>
                    </div>
                    <div class="col-md-6" align="center">
                        <p style="font-size:25px;"><strong>{{obj.last_name}} {{obj.first_name}}</strong><p>
                        <h1 class="g-color-gray-dark-v4 g-font-size-12">{{obj.country}}</h1>
                        <a href={{obj.get_absolute_url}}><button class="btn btn-outline-primary">See profile</button></a>
                    </div>
                    <div class="col-md-3"></div>            
                </div>
                <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-6"></div>
                    <div class="col-md-3" align="right">
                        <!-- Se l'utente non fa parte della lista invitati o ricezione inviti allora è un utente al quale è possibile inviare una richiesta-->
                        {% if obj.user not in list_sender and obj.user not in list_receiver %}
                            <form action="{% url 'profiles:send-invite' %}" method="POST">
                            {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit" class="btn btn-outline-success"> Add friend </button>
                            </form>
                        {% endif %}

                        <!-- Se un utente è nella lista invitati, su di esso viene mostrato un messaggio che indica l'attesa della conferma di amicizia-->
                        {% if obj.user in list_receiver and request.user not in obj.friends.all %}
                            <button class="ui disabled button">Waiting for approval</button>
                        {% endif %}

                        <!-- Se tale utente fa già parte della lista degli amici dell'utente corrente, viene mostrato un bottone che permette la rimozione di tale utente se necessario-->
                        {% if request.user in obj.friends.all %}
                            <form action="{% url 'profiles:remove-friend' %}" method="POST">
                            {% csrf_token %}
                                <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                <button type="submit"class="btn btn-outline-danger"> Remove friend </button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock content %}

src/profiles/templates/profiles/changePassword.html
{% extends 'base.html' %}

{% block title %} my profile {% endblock title %}

{% block content %}
{% if error == False and message != '' %}
<div class="alert alert-success" role="alert">
  <strong>Success!</strong> {{ message }}
</div>
{% elif error == True and message != '' %}
<div class="alert alert-danger" role="alert">
  <strong>Warning!</strong> {{ message }}
</div>
{% endif %}
<center><h1> Change your password</h1>
<div id="containerChangePWD" class="container">
  <form>
    <div class="row">
      <div class="col-lg-2"></div>
      <div class="col-lg-8 text-center">
        <label>New Password</label><br>
        <input type="password" id="newPWD" name="newPWD" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}" title="Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters" required>
      </div>
      <div class="col-lg-2"></div>
    </div>
    <div class="row">
      <div class="col-lg-2"></div>
      <div class="col-lg-8 text-center">
        <label>Confirm Password</label><br>
        <input type="password" id="confirmPWD" name="confirmPWD" required>
      </div>
      <div class="col-lg-2"></div>
    </div>
    <div class="row">
      <div class="col-lg-2"></div>
      <div class="col-lg-8 text-center">
        <form action="{% url 'profiles:change-password' %}" method="POST" >
          {% csrf_token %}
          <button class="btn btn-danger"> Update Password </button>
      </div>
      <div class="col-lg-2"></div>
        </form>
    </div>
  </form>
</div>
{% endblock content %}

src/profiles/templates/profiles/chat.html
{% extends 'base.html' %}

{% block title %} Search {% endblock title %}

{% block content %}
{% load static %}
<main class="content">
    <div class="container p-0" id="chatContainer">
		<div class="card" id="cardChat">
			<div class="row g-0">
				<div class="col-12 col-lg-5 col-xl-3 border-right">
					{% for userConv,count in userConversation %}
					<form action="{% url 'profiles:chat-view' %}" method="POST">
						{% csrf_token %}
						<input type="hidden" name="profile_pk" value={{userConv.pk}}>
						<button class="list-group-item list-group-item-action border-0">
							<div class="d-flex align-items-start border-top">
								<img src="{{ userConv.avatar.url }}" class="rounded-circle mr-1" width="40" height="40">
								<div class="flex-grow-1 ml-3">
									{{ userConv.first_name }} {{ userConv.last_name }}
								</div>
							</div>
							{% if count > 0 %}
								<div class="badge bg-success float-right"> {{count}} </div>
							{% elif count == 0 %}
								<div class="badge bg-danger float-right"> {{count}} </div>
							{% endif %}
						</button>
					</form>
					{% endfor %}
					<hr class="d-block d-lg-none mt-1 mb-0">
				</div>
				<div class="col-12 col-lg-7 col-xl-9">
					<div class="py-2 px-4 border-bottom d-none d-lg-block">
						<div class="d-flex align-items-center py-1">
							<div class="position-relative">
								{% if user.avatar.url %}
									<img src="{{ user.avatar.url }}" class="rounded-circle mr-1" width="40" height="40">
								{% endif %}
								{% if not user.avatar.url %}
									<img src="{% static 'Images/logo_white_large.png' %}" class="rounded-circle mr-1" width="40" height="40">
								{% endif %}
							</div>
							<div class="flex-grow-1 pl-3">
								<strong> {{ user.first_name }} {{ user.last_name}} </strong>
							</div>
						</div>
					</div>
					<div class="position-relative">
						<div class="chat-messages p-4">
						{% for message in messages %}
							{% if message.flag %}
							<div class="chat-message-right pb-4">
								<div>
									<img src="{{ message.sender_message.avatar.url }}" class="rounded-circle mr-1" alt="Chris Wood" width="40" height="40">
									<div class="text-muted small text-nowrap mt-2"> {{ message.created }} </div>
								</div>
								<div class="flex-shrink-1 bg-light rounded py-2 px-3 mr-3">
									<div class="font-weight-bold mb-1">{{ message.sender_message.first_name }} {{ message.sender_message.last_name}}</div>
									{{ message.content }}
								</div>
							</div>
							{% endif %}
							{% if not message.flag %}
							<div class="chat-message-left pb-4">
								<div>
									<img src="{{ message.sender_message.avatar.url }}" class="rounded-circle mr-1" alt="Sharon Lessman" width="40" height="40">
									<div class="text-muted small text-nowrap mt-2"> {{ message.created }} </div>
								</div>
								<div class="flex-shrink-1 bg-light rounded py-2 px-3 ml-3">
									<div class="font-weight-bold mb-1"> {{ message.sender_message.first_name }} {{ message.sender_message.last_name}}</div>
									{{ message.content }}
								</div>
							</div>
							{% endif %}
						{% endfor %}
						</div>
					</div>
					<form action="{% url 'profiles:send-message' %}" method="POST">
						<div class="flex-grow-0 py-3 px-4" id="sendMessageContainer">
							<div class="input-group">
								{% csrf_token %}
									<input type="hidden" name="profile_pk" value={{user.pk}}>
									<input type="text" name="content_message" class="form-control" placeholder="Type your message">
									{% if user %}
									<button class="btn btn-primary">Send</button>
									{% elif not user %}
									<button class="btn btn-primary" disabled>Send</button>
									{% endif %}
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</main>

{% endblock content %}

src/profiles/templates/profiles/myInvites.html
{% extends 'base.html' %}

{% block title %} My invites{% endblock title %}

{% block content %}

{% if is_empty %}
<div id="sadContainer" class="container" align="center">
    <div class="row">
      <div class="col-md-2"></div>
      <div id="sadMessages" class="col-md-8">  
        <strong> <h1> No invitations yet </h1> </strong>
        <i class="bi bi-emoji-frown">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="currentColor" class="bi bi-emoji-frown" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683zM7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z"/>
            </svg>
        </i>
      </div>
      <div class="col-md-2"></div>
    </div>
</div>
{% endif %}


<br>
{% for obj in qs %}
<div id="myinvitesContainer" class="ui container">
    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="col-md-3">
                    <center><img class = "ui small circular image" src={{obj.avatar.url}}></center>
                </div>
                <div class="col-md-9">
                    <h3>{{obj.user}}</h3>
                    <p>{{obj.bio}}</p>
                    <div class="container"></div>
                        <div class="row">
                            <div class="col-md-4">
                                <form action="{% url 'profiles:show-profile' %}" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button class="btn btn-primary">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                                            <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                            <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                        </svg>
                                            See Profile
                                    </button>
                                </form>
                            </div>
                            <div class="col-md-4">
                                <!--Form per accettare una richiesta di amicizia-->
                                <form action="{% url 'profiles:accept-invite' %}" method="POST">
                                {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class="btn btn-outline-success" style="height:30px;width:150px">
                                        <i class="check icon"></i>
                                            Accept invite
                                    </button>
                                </form>
                            </div>
                            <div class="col-md-4">
                                <!--Form per rifiutare una richiesta di amicizia-->
                                <form action="{% url 'profiles:reject-invite' %}" method="POST">
                                {% csrf_token %}
                                    <input type="hidden" name="profile_pk" value={{obj.pk}}>
                                    <button type="submit" class="btn btn-outline-danger" style="height:30px;width:150px;">
                                        <span aria-hidden="true">&times;</span>
                                            Reject invite
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock content %}

src/profiles/templates/profiles/searchedProfileInfo.html
{% extends 'base.html' %}

{% block title %} Search {% endblock title %}

{% block content %}

<div id="searchedProfileCard" class="card">
    <div id="cardContainer" class="container">
        <center><img class = "ui small circular image" src="{{ profile.avatar.url }}"></center>
        <h1> {{profile.last_name}} {{ profile.first_name}} </h1>
        <p class="title"> {{ profile.bio }} </p>
        <p> {{ profile.country }} </p>
        {% if check and not req and not notFriend %}
            <div class="container">
                <div class="row">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-3">
                        <form action="{% url 'profiles:chat-view' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{profile.pk}}>
                            <button type="submit" class="btn btn-info" style="height:30px;width:150px">
                                Send Message
                            </button>
                        </form>
                    </div>
                    <div class="col-lg-3">
                        <form action="{% url 'profiles:delete-friend-view' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{profile.pk}}>
                            <button type="submit" class="btn btn-danger" style="height:30px;width:150px">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                                    Remove Friend
                            </button>
                        </form>
                    </div>
                    <div class="col-lg-3"></div>
                </div>
            </div>
        {% elif not check %}
            {% if not req and not notFriend %}
                <form action="{% url 'profiles:accept-invite-view' %}" method="POST">
                {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{profile.pk}}>
                    <button type="submit" class="btn btn-success"> Accept Invite </button>
                </form>
            {% endif %}

            {% if req and not notFriend%}
                <button class="ui disabled button">Waiting for approval</button>
            {% endif %}

            {% if notFriend and not req%}
                <form action="{% url 'profiles:send-invite' %}" method="POST">
                {% csrf_token %}
                    <input type="hidden" name="profile_pk" value={{profile.pk}}>
                    <button type="submit" class="btn btn-dark"> Send Request </button>
                </form>
            {% endif %}
        {% endif %}
    </div>
</div>

{% endblock content %}

src/profiles/templates/profiles/toInvites.html
{% extends 'base.html' %}

{% block title %} All profiles available to send an invitation {% endblock title %}

{% block content %}
<ul>
    {% for item in qs %}<li>{{item}}{% endfor %}
</ul>
{% endblock content %}