src/feisgram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, signup

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include('allauth.urls')),
    path('accounts/signup', signup, name='account_signup'),
    path('profiles/', include('profiles.urls', namespace = 'profiles')),
    path('posts/', include('posts.urls', namespace='posts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

src/posts/urls.py
from django.urls import path
from .views import post_comment_create_list, like_unlike_post, PostDeleteView, PostUpdateView

app_name = 'posts'

urlpatterns = [
    path('', post_comment_create_list, name = 'main-post-view'),
    path('liked/', like_unlike_post, name = 'like-post-view'),
    path('<pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<pk>/update/', PostUpdateView.as_view(), name='post-update'),
]

src/posts/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from profiles.models import Profile

# Create your models here.

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to = 'posts', blank=True, validators = [FileExtensionValidator(['png','jpg','jpeg'])])
    liked = models.ManyToManyField(Profile, blank=True, related_name = 'likes')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.content)

    '''
        Funzione che ritorna il numero complessivo dei like relativi ad un determinato utente
    '''

    def num_likes(self):
        return self.liked.all().count()

    '''
        Per contare il numero di commenti sotto ad un post non ho un riferimento all commento nella tabella post
        quindi faccio uso della seguente clausola 'comment_set' che fa riferimento a tutti i commenti 
        di un relativo post, questo avviene grazie alla relazione nata dalla dichiarazione della chiave esterna dalla tabella
        'comment' verso la tabella 'posts'
    '''

    def num_comments_on_post(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created',)
    
class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)

LIKE_CHOICES = (
    ('like', 'like'),
    ('unlike','unlike'),
)

class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"
    
    

src/posts/forms.py
from django import forms
from .models import Post, Comment

class PostModelForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={'rows':3}))
    class Meta:
        model = Post
        fields = ('content', 'image')

class CommentModelForm(forms.ModelForm):
    body = forms.CharField(label='', 
                            widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))
    class Meta:
        model = Comment
        fields = ('body',)

src/posts/views.py
from multiprocessing import current_process
from django.core.checks import messages
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
#from jmespath import search
from matplotlib.pyplot import title
from .models import Post, Like
from profiles.models import Profile
from django.contrib.auth.models import User
from .forms import PostModelForm, CommentModelForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

@login_required
def post_comment_create_list(request):

    search_query = request.GET.get('search', '')
    friends = request.user.friends.all()
    ''' Prelevo la lista degli amici '''
    if search_query:
        qs = Post.objects.filter(content__icontains=search_query)
    else:
        qs = Post.objects.filter(author=Profile.objects.get(user=request.user))
        for item in friends:
            qs |= Post.objects.filter(author=item).order_by('-created')
    profile = Profile.objects.get(user=request.user)

    # initials
    p_form = PostModelForm()
    c_form = CommentModelForm()
    post_added = False

    profile = Profile.objects.get(user=request.user)

    if 'submit_p_form' in request.POST:
        p_form = PostModelForm(request.POST, request.FILES)
        if p_form.is_valid():
            instace = p_form.save(commit=False)
            instace.author = profile
            instace.save()
            p_form = PostModelForm()
            post_added = True

    if 'submit_c_form' in request.POST:
        c_form = CommentModelForm(request.POST)
        if c_form.is_valid():
            instace = c_form.save(commit=False)
            instace.user = profile
            instace.post = Post.objects.get(id=request.POST.get('post_id'))
            instace.save()
            c_form = CommentModelForm

    context = {
        'qs' : qs,
        'profile' : profile,
        'p_form' : p_form,
        'c_form' : c_form,
        'post_added' : post_added,
    }

    return render(request, 'posts/myPosts.html', context)

@login_required
def like_unlike_post(request):
    '''
        Utente loggato
    '''
    user = request.user
    if request.method == 'POST':
        '''
            Prelevo l'id del post tramite una request dal form presente in myPosts.html
        '''
        post_id = request.POST.get('post_id')
        ''' 
            Avendo prelevato l'id del post ora abbiamo bisogno del post in termmine di oggetto 
        '''
        post_obj = Post.objects.get(id=post_id)
        '''
            Nel modello i like sono di tipo many-to-many ed hanno bisogno di conoscere il profilo collegato da non confondere con l'utente loggato
        '''
        profile = Profile.objects.get(user=user)
        '''
            Controllo se un determinato profilo ha messo il like al post scelto
        '''
        if profile in post_obj.liked.all():
            '''
                Se il profilo è presente una volta che si clicca sul tasto allora esso deve essere rimosso 
                Morale: se il profilo ha già messo il like e clicca di nuovo il tasto esso e come se rimuovesse il like
            '''
            post_obj.liked.remove(profile)
        else:
            '''
                Altrimenti se il profilo non è presente nei like esso viene aggiunto
            '''
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile,post_id = post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        else:
            like.value = 'Like  '
            post_obj.save()
            like.save()

        data = {
            'value': like.value,
            'likes': post_obj.liked.all().count()
        }
        return JsonResponse(data, safe=False)


    return redirect('posts:main-post-view')

    
class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'posts/confirm_del.html'
    success_url = reverse_lazy('posts:main-post-view')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.Warning(self.request, 'You need to be author of the post in order to delete it')
        return obj

class PostUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PostModelForm
    model = Post
    template_name = 'posts/update.html'
    success_url = reverse_lazy('posts:main-post-view')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, "You need to be author of the post in order to update it")
            return super().form_invalid(form)

src/posts/templates/posts/confirm_del.html
{% extends 'base.html' %}

{% block title %}
    delete post
{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class='ui negative  message'>
                    <div class="header">
                        {{messages}}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if not message %}
        <div class="container" align="center">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">  
                    <h3>Delete post</h3>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <p> Are you sure you want to delete the post <p>
                        <button type='submit' class="btn btn-danger">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                            </svg>
                            Delete
                        </button>
                    </form>
                </div>
                <div class="col-md-2"></div>
            </div>
        </div>
    {% endif %}
{% endblock content %}

src/posts/templates/posts/myPosts.html
{% extends 'base.html' %}

{% block title %} posts {% endblock title %}
{% block content %} 

<div class="container" id="form_s">
  <div class="row">
      <div class="col-lg-2"></div>
      <div class="col-lg-8">
          <form class="ui form" action="{% url 'posts:main-post-view' %}">
              {% csrf_token %}
              <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="search">
      </div>
      <div class="col-lg-2"><button type='submit' class='btn btn-danger'>Search</button></div>
            </form>
  </div>
</div>

<div class="container">
<div class="row">
    <div id="formPosts" class="col-md-12">
      <div class="modal-body">
      <h3 class="modal-title" id="exampleModalLongTitle">Add new post</h3>
      {% if post_added %}
        <div class="container"> Post added</div>
      {% endif %}
        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
          {% csrf_token %}
          {{p_form}}
          <div class="modal-footer">
            <button type='submit' class='btn btn-danger' name="submit_p_form"> 
                Send Post
            </button>
          </div>
        </form>
      </div>
    </div>
</div>
<div class="row">
<div id="conteinerPosts" class="col-md-12">
    {% for obj in qs %}
      <div id="Cposts" class="col-md-12">
        <div class="media g-mb-30 media-comment">
            <img class="d-flex g-width-50 g-height-50 rounded-circle g-mt-3 g-mr-15" src={{obj.author.avatar.url}} alt="Image Description">
            <div class="media-body u-shadow-v18 g-bg-secondary g-pa-30">
              <div class="row">
                <div class="col-md-4">
                  <p><strong>{{obj.author.first_name}} {{obj.author.last_name}}</strong></p>
                </div>
                <div class="col-md-4"></div>
                <div class="col-md-4" align="right">
                  <h1 class="g-color-gray-dark-v4 g-font-size-12">(Posted {{obj.created}})</h1>
                </div>
              </div>
              <div id="ContentPost" class="row">
                <div class="col-md-12">
                      <strong>{{obj.content}}</strong>
                </div>
              <div class="row">
                <div id="postImageContainer" class="container">
                  <div class="col-md-12">
                    {% if obj.image %}
                      <center><image id="postImage" src="{{obj.image.url}}"></image></center>
                    {% endif %}
                  </div>
                </div>
              </div>
              </div>
              <div id="CLikes"class="row">
                <div class="col-md-1" align="left">
                  <h1 class="g-color-gray-dark-v4 g-font-size-12"><div class="like-count{{obj.id}}">&nbsp;{{obj.num_likes}}<i class="thumbs up icon"></i></h1>
                </div>
                <div class="col-md-9"></div>
                <div class="col-md-2" align="right">
                  <form id="{{obj.id}}" action="{% url 'posts:like-post-view' %}" method="POST" class ='like-form'>
                  {% csrf_token %}
                      <input type="hidden" name='post_id' value={{obj.id}}>
                      <button type="submit" class="btn btn-outline-danger like-btn{{obj.id}}" formmethod="post">
                      {% if profile not in obj.liked.all %}
                          <i class="thumbs up icon"></i>&nbsp; Like
                      {% else %}
                          <i class="thumbs down icon"></i>&nbsp; Unlike
                      {% endif %}
                      </button>
                  </form>
                </div>
              </div>
              <div class="extra content">
                <button class="cmt_btn btn btn-outline-secondary">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                        <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"/>
                        <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/>
                    </svg>
                </button>
                    <div id="CComments" class="comment-box row">
                        <div class="col-md-12">
                            {% if obj.comment_set.all %}
                                {% for c in obj.comment_set.all %}
                                    <div class="media g-mb-30 media-comment">
                                        <div id="ContentPost" class="media-body u-shadow-v18 g-bg-secondary g-pa-30" align="center">
                                            <img class="ui avatar image" src={{c.user.avatar.url}}>
                                            <p><b>{{ c.user.first_name }} {{c.user.last_name}}</b></p>  
                                            <p>{{c.body}}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <form action="" method="POST" class="ui form">
                            {% csrf_token %}
                                <input type="hidden" name="post_id" value={{obj.id}}>
                                {{c_form}}
                        </div>
                    </div>
              </div>
              <div id="ButtonSend" class="row">
                <div class="col-md-12" align="right">
                    <button type='submit' class='btn btn-outline-danger' name="submit_c_form"><i class="comment icon"></i>Send </button>
                </div>
              </div>
              </form>
              <div id="ButtonUpdateDelete" class="row" align="center">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    {% if request.user == obj.author.user %}
                            <a href="{% url 'posts:post-update' obj.pk %}">
                                <button class="btn btn-outline-secondary">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eraser-fill" viewBox="0 0 16 16">
                                        <path d="M8.086 2.207a2 2 0 0 1 2.828 0l3.879 3.879a2 2 0 0 1 0 2.828l-5.5 5.5A2 2 0 0 1 7.879 15H5.12a2 2 0 0 1-1.414-.586l-2.5-2.5a2 2 0 0 1 0-2.828l6.879-6.879zm.66 11.34L3.453 8.254 1.914 9.793a1 1 0 0 0 0 1.414l2.5 2.5a1 1 0 0 0 .707.293H7.88a1 1 0 0 0 .707-.293l.16-.16z"/>
                                    </svg>
                                    Update
                                </button>
                            </a>
                            <a href="{% url 'posts:post-delete' obj.pk %}">
                                <button class="btn btn-outline-danger">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                    </svg>
                                    Delete 
                                </button>
                            </a>
                    {% endif %}
                </div>
                <div class="col-md-3"></div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
     </div>
</div>
</div>
{% endblock content %}

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.0.0.js"></script>
<script>
  $( document ).ready(function() {
      let display = false
      $(".cmt_btn").click(function () {
          if (display===false) {
              $(this).next(".comment-box").show("slow");
              display=true
          } else {
              $(this).next(".comment-box").hide("slow");
              display=false
          }  
      });

      $('.like-form').submit(function(e){
          e.preventDefault()
          
          const post_id = $(this).attr('id')
          
          const likeText = $(`.like-btn${post_id}`).text()
          const trim = $.trim(likeText)

          const url = $(this).attr('action')
          
          let res;
          const likes = $(`.like-count${post_id}`).text()
          const trimCount = parseInt(likes)
          
          $.ajax({
              type: 'POST',
              url: url,
              data: {
                  'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
                  'post_id':post_id,
              },
              success: function(response) {
                  if(trim === 'Unlike') {
                      $(`.like-btn${post_id}`).text('Like')
                      res = trimCount - 1
                  } else {
                      $(`.like-btn${post_id}`).text('Unlike')
                      res = trimCount + 1
                  }

                  $(`.like-count${post_id}`).text(res)
              },
              error: function(response) {
                  console.log('error', response)
              }
          })

      })
  });
</script>
{% endblock scripts %}

src/posts/templates/posts/update.html
{% extends 'base.html' %}

{% block title %}
    update post
{% endblock title %}

{% block content %}
<div class="container">
    <div id="formPosts" class="col-md-12">
        <div class="modal-body">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8">  
                    <h3>Update post</h3>
                        <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form}}
                </div>
                <div class="col-md-2"></div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-8" align="right">
                    <button type="submit" class="btn btn-danger" align="right">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eraser-fill" viewBox="0 0 16 16">
                            <path d="M8.086 2.207a2 2 0 0 1 2.828 0l3.879 3.879a2 2 0 0 1 0 2.828l-5.5 5.5A2 2 0 0 1 7.879 15H5.12a2 2 0 0 1-1.414-.586l-2.5-2.5a2 2 0 0 1 0-2.828l6.879-6.879zm.66 11.34L3.453 8.254 1.914 9.793a1 1 0 0 0 0 1.414l2.5 2.5a1 1 0 0 0 .707.293H7.88a1 1 0 0 0 .707-.293l.16-.16z"/>
                        </svg>
                        Update
                    </button>
                </div>
                <div class="col-md-2"></div>
            </div>
                        </form>
        </div>
    </div>
</div>
{% endblock content %}